# Generated by Django 3.1.3 on 2020-11-30 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[('ruim', 'Ruim'), ('bom', 'Bom'), ('muito_bom', 'Muito Bom'), ('excelente', 'Excelente')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Criterict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterict', models.CharField(max_length=100, verbose_name='Criterio')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criterict.experience')),
            ],
        ),
    ]
