# Generated by Django 3.1.3 on 2020-11-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criterict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criterict',
            name='criterict',
            field=models.CharField(blank=True, max_length=100, verbose_name='Criterio'),
        ),
    ]
