# Generated by Django 3.1.3 on 2020-11-30 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('criterict', '0001_initial'),
        ('jobs', '0002_auto_20201124_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='criterict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='criterict.criterict'),
            preserve_default=False,
        ),
    ]
