# Generated by Django 3.1.3 on 2020-11-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201124_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterict', models.CharField(blank=True, max_length=100, verbose_name='Criterio')),
                ('experience', models.CharField(choices=[('ruim', 'Ruim'), ('bom', 'Bom'), ('muito_bom', 'Muito Bom'), ('excelente', 'Excelente')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='jobs',
            name='criterict',
            field=models.ManyToManyField(to='jobs.Criterict'),
        ),
    ]
