# Generated by Django 3.1.3 on 2020-11-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20201130_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='experience',
            field=models.CharField(choices=[('ruim', 'Ruim'), ('bom', 'Bom'), ('muito_bom', 'Muito Bom'), ('excelente', 'Excelente')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='jobs',
            name='criterict',
        ),
        migrations.AddField(
            model_name='jobs',
            name='criterict',
            field=models.CharField(blank=True, max_length=100, verbose_name='Criterio'),
        ),
        migrations.DeleteModel(
            name='Criterict',
        ),
    ]
