# Generated by Django 3.1.3 on 2020-12-01 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20201130_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='criterict',
        ),
        migrations.AddField(
            model_name='jobs',
            name='criterict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.criterio'),
            preserve_default=False,
        ),
    ]
