# Generated by Django 3.1.3 on 2020-12-01 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0006_auto_20201130_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='candidate',
            field=models.ManyToManyField(related_name='Candidato', to=settings.AUTH_USER_MODEL),
        ),
    ]
