# Generated by Django 3.1.3 on 2020-12-01 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0007_jobs_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='candidate',
        ),
        migrations.CreateModel(
            name='Aplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aplication',
                'verbose_name_plural': 'Aplications',
                'unique_together': {('user', 'jobs')},
            },
        ),
    ]
