# Generated by Django 3.1.3 on 2020-12-02 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20201201_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterio',
            name='experience',
        ),
    ]
