# Generated by Django 3.1.3 on 2020-12-02 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0010_remove_jobs_criterict'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customusuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='criterict',
            field=models.ManyToManyField(to='jobs.Criterio'),
        ),
        migrations.AlterField(
            model_name='criterio',
            name='criterict',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Criterio'),
        ),
    ]
