# Generated by Django 3.1.3 on 2020-12-07 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_aplication_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='criterict',
        ),
        migrations.AddField(
            model_name='jobs',
            name='criterict',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobs.criterio'),
            preserve_default=False,
        ),
    ]
