# Generated by Django 3.1.3 on 2020-12-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_auto_20201206_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='criterio',
            name='experience',
            field=models.CharField(choices=[('ruim', 'Ruim'), ('bom', 'Bom'), ('muito_bom', 'Muito Bom'), ('excelente', 'Excelente')], default=1, max_length=20, verbose_name='Criterio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='contract_type',
            field=models.CharField(choices=[('clt', 'CLT'), ('temporario', 'Temporario'), ('freelance', 'Freelance'), ('home_office', 'Home Office')], max_length=20, verbose_name='Tipo de Contrato'),
        ),
    ]
