# Generated by Django 3.1.3 on 2020-12-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_criterio_user'),
        ('answer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answercriterict',
        ),
        migrations.AddField(
            model_name='answer',
            name='criterict',
            field=models.ManyToManyField(to='jobs.Criterio'),
        ),
        migrations.AddField(
            model_name='answer',
            name='experience',
            field=models.CharField(choices=[('ruim', 'Ruim'), ('bom', 'Bom'), ('muito_bom', 'Muito Bom'), ('excelente', 'Excelente')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
