# Generated by Django 3.1.3 on 2020-12-07 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_auto_20201206_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='criterict',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='jobs',
        ),
        migrations.DeleteModel(
            name='AnswerCriterict',
        ),
    ]
