# Generated by Django 3.1.3 on 2020-12-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_auto_20201206_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='user',
        ),
    ]
