# Generated by Django 3.1.3 on 2020-12-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0005_remove_answer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='experience',
            field=models.CharField(choices=[('ruim', 'Ruim'), ('bom', 'Bom'), ('muito_bom', 'Muito Bom'), ('excelente', 'Excelente')], max_length=20, verbose_name='Criterio'),
        ),
    ]
